import localFont from "next/font/local";
import dynamic from "next/dynamic";
import "./globals.css";
import "./app.css"

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Staking Rewards DApp",
  description: "Generated by create next app",
};

const Web3Provider = dynamic(() => import("../context/Web3Provider"), { ssr: false });
const Connector = dynamic(() => import("../components/Connector"), { ssr: false });
const StakingRewardsProvider = dynamic(() => import("../context/contract"), { ssr: false });

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased p-5`}
      >
        <Web3Provider>
          <Connector>
            <StakingRewardsProvider>
              {children}
            </StakingRewardsProvider>
          </Connector>
        </Web3Provider>
      </body>
    </html>
  );
}
